### ISSUE TITLE
Issue with low level handshake

### ISSUE THREAD

**Issue by schoeppi5** [ReSpeak/tsdeclarations#60]
I have an issue with the low level handshake. I managed to build the first init packet and recieved the second init packet. The weird thing is, that the server has the compressed flag set and judging from the data, it is not compressed. However, the data contains the number (0x01) and then it follows with (0x00 0x00 0x02 \n) and then all zeros? I am using server version 3.13.3 running in docker although I get the same result with it running in podman and on bare linux

As you can imagine I cannot complete the handshake, since the server doesn't respond with a package when I try sending the third init package. I think something changed or at least works differently than you described in your document. Do you have any insight in what is going on here and possibly even how I should continue?

**Comment by Splamy** [comment]
Ah yes, this is indeed a package variation we found later and haven't updated to the dec again yet.
You can see how the TSLib handles this here: https://github.com/Splamy/TS3AudioBot/blob/master/TSLib/Full/TsFullClient.cs#L193-L202
Basically the server tells you that it doesn't like your first packet for whatever reason. You can read the following 4 bytes as a LittleEndian int to get the [ts3 error code](https://github.com/ReSpeak/tsdeclarations/blob/master/Errors.csv)
So in your case, if your info is correct it should be error 0x200 which means `client_invalid_id`, which seems strange.
Make sure the next byte really is all zeros and not 0x0A, which would be the error 0x020a = client_version_outdated. This was the case how we found it. This happens when the `Version of the TeamSpeak client as timestamp` is too old for the server (and when you copied the example version from the doc this is most probably what happend). As an easy workaround, read the bottom note of [here](https://github.com/ReSpeak/tsdeclarations/blob/master/ts3protocol.md#2-the-low-level-initiationhandshake) and use the current time to generate a new version when creating the packet.

**Comment by schoeppi5** [comment]
Thanks for your response. I already found out, that I was building the second packet wrong and updated the client version to 3.5.6. The thing is I still get the thing with one byte set followed by fifteen zero bytes. The interesting part though is, that I had a look at the handshake performed by the official client using wireshark and found out, that it looks just like that. Only differences I could spot this far are: The client starts the low level handshake and the crypto handshake at the same time (I think. The client sends the first low level handshake packet followed immediately with a different packet I can at this point just assume is the first crypto handshake packet) and the server answers the third low level handshake packet as expected, even though the client also recieved one set byte followed by fifteen zero bytes as the second packet. I am not really sure why that is. I will have a look into the error code thing you were talking about. Thanks so far

**Comment by schoeppi5** [comment]
Ok I figured it out. I am the worst kind of stupid. I misscalculated the length of the byte array in two locations. Thats why the fist packet got accepted and the second didn't the last byte was missing.
